global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'mcp-material'
    metrics_path: /metrics
    static_configs:
      - targets: ['mcp-material:8080']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
